<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUURHr5x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUURHr5x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUURHr5x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUURHr5x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUURHr5x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UURHr5x',
    'container.build_id' => 'e0276810',
    'container.build_time' => 1587310586,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUURHr5x');
